-- castmember table rows
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (1, 'Heather', 'Haigh', '717-316-4106', false, false, null, null);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (2, 'Michele', 'Long', '570-263-0378', true, false, null, null);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (3, 'Kyle', 'Haigh', '570-295-6285', false, true, null, null);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (4, 'Andrew', 'Haigh', '570-927-2146', true, true, null, null);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Jocelyn', 'Cunningham', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Melody', 'Watson', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Emilee', 'Eisner', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Laurel', 'Demers', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Kira', 'Bierly', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Rees', 'Bierly', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Sarah', 'Andrus', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Grace', 'Welshans', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);
INSERT INTO castmember (castmember_id, first_name, last_name, phone_number, tap_performer, costume_complete, new_first_name, new_last_name) VALUES (NULL, 'Briar', 'Cohick', DEFAULT, DEFAULT, DEFAULT, NULL, NULL);

-- part table rows
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (1, 'Wicked', 1, 'Director', null);
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (2, 'Wicked', 1, 'Elphaba', null);
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (3, 'Wicked', 2, 'Glinda', null);
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (4, 'Wicked', 3, 'Fiero', null);
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (5, 'Wicked', 4, 'The Wizard', null);

INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (1, 'Nunsense', 8, 'Reverend Mother', 'Leads');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (2, 'Nunsense', 12, 'Sister Mary Hubert', 'Leads');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (3, 'Nunsense', DEFAULT, 'Sister Robert Anne', 'Leads');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (4, 'Nunsense', 5, 'Sister Mary Amnesia', 'Leads');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (5, 'Nunsense', 13, 'Sister Mary Leo', 'Leads');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (6, 'Nunsense', 9, 'Sister Julia, Child of God', 'Named');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (7, 'Nunsense', DEFAULT, 'Sister Mary Brendan', 'Named');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (8, 'Nunsense', 10, 'Sister Mary Luke', 'Named');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (9, 'Nunsense', 11, 'Sister Mary Wilhelm', 'Named');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (10, 'Nunsense', DEFAULT, 'Father Virgil', 'Named');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (11, 'Nunsense', DEFAULT, 'Brother Timothy','Stagehand');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (12, 'Nunsense', DEFAULT, 'Chorus Nun #1', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (13, 'Nunsense', DEFAULT, 'Chorus Nun #2', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (14, 'Nunsense', DEFAULT, 'Chorus Nun #3', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (15, 'Nunsense', DEFAULT, 'Chorus Nun #4', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (16, 'Nunsense', DEFAULT, 'Chorus Nun #5', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (17, 'Nunsense', DEFAULT, 'Chorus Nun #6', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (18, 'Nunsense', DEFAULT, 'Chorus Nun #7', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (19, 'Nunsense', DEFAULT, 'Chorus Priest', 'Chorus Nuns');
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (20, 'Nunsense', 1, 'Sister Mary Patrick', null);
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (21, 'Nunsense', DEFAULT, 'Sister Mary Contrary', null);
INSERT INTO part (part_number, musical_name, castmember_id, character_name, character_group) VALUES (22, 'Nunsense', 3, 'Sister Mary Paul', null);

-- scene table rows
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Wicked', 1, 'Opening Scene', null, null, '1', 'childhood home of Elphaba', 1, 3);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Wicked', 2, 'Shizz', 'Dear Old Shizz', 3, '1', 'outside of Shizz', 4, 6);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Wicked', 3, 'Make a Date', 'Dancing Through Life', 6, '1', 'foyer at Shizz', 7, 9);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Wicked', 4, 'Friends Forever', 'For Good', 17, '2', 'Oz', 67, 68);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense: The Mega-Musical Version', 1, 'A Difficult Transition', 'A Difficult Transition', 4, 'I', 'Mount Saint Helens School Gym', 12, 15);

INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense',100, 'Overture', 'Overture', 00, 'I', 'Pit/Audience Aisles', 7, 8);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 1, 'Overture cont.', 'Overture', 00, 'I', 'Upstage Center', 8, 9);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 2, 'Veni Creator Spiritus', 'Veni Creator Spiritus', 2, 'I', 'Mount Saint Helens School Gym', 9, 9);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 3, 'Nunsense is Habit Forming', 'Nunsense is Habit Forming', 3, 'I', 'Mount Saint Helens School Gym', 10, 12);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 4, 'ConventHistory', null, null, 'I', null, 12, 14);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 5, 'A Difficult Transition', 'A Difficult Transition', 4, 'I', 'Mount Saint Helens School Gym', 14, 19);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 6, 'Quiz', 'Quiz Timer(05A)/Quiz Fanfare(5B)/Quiz Fanfare(5C)', 5, 'I', 'Mount Saint Helens School Gym', 19, 23);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 7, 'Benedicite', 'Benedicite', 6, 'I', 'Mount Saint Helens School Gym', 23, 25);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 8, 'The Biggest Ain\'t the Best', 'The Biggest Ain\'t the Best (07)', 7, 'I', 'Mount Saint Helens School Gym', 25, 28);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 9, 'Robert Anne\'s Surprise(08)/Another Surprise (08A)', 'Robert Anne\'s Surprise(08)/Another Surprise (08A)', 8, 'I', 'Mount Saint Helens School Gym', 28, 29);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 10, 'Playing Second Fiddle (09)/Second Fiddle Conclusion(09A)', 'Playing Second Fiddle (09)/Second Fiddle Conclusion(09A)', 9, 'I', 'Mount Saint Helens School Gym', 29, 31);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 11, 'Julia\'s Pressed Duck', null, null, 'I', 'Mount Saint Helens School Gym', 31, 33);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 12, 'So You Want To Be A Nun', 'So You Want To Be A Nun', 10, 'I', 'Mount Saint Helens School Gym', 34, 37);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 13, 'Nun Playoff', 'Nun Playoff(10A)', 10, 'I', 'Mount Saint Helens School Gym', 37, 38);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 14, 'Mock Fifties', 'Mock Fifties', 11, 'I', 'Mount Saint Helens School Gym', 38, 39);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 15, 'A Good Cause', 'A Good Cause(11A)', 11, 'I', 'Mount Saint Helens School Gym', 39, 40);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 16, 'The Voicemail', null, null, 'I', 'Mount Saint Helens School Gym', 40, 41);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 17, 'Turn Up The Spotlight', 'Turn Up The Spotlight', 12, 'I', 'Mount Saint Helens School Gym', 41, 44);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 18, 'Spotlight Playoff', 'Spotlight Playoff(12A)', 12, 'I', 'Mount Saint Helens School Gym', 44, 44);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 19, 'Lilacs Bring Back Memories/The Witch', 'Lilacs Bring Back Memories/The Witch', 13, 'I', 'Mount Saint Helens School Gym', 45, 46);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 20, 'Prepare for Act I Finale', null, null, 'I', 'Mount Saint Helens School Gym', 46, 49);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 21, 'Turn Off That Spotlight', 'Turn Off That Spotlight', 15, 'I', 'Mount Saint Helens School Gym', 49, 50);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 22, 'Tackle That Temptation', 'Tackle That Temptation', 16, 'I', 'Mount Saint Helens School Gym', 50, 52);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 23, 'Chorus Jokes', null, null, 'II', 'Mount Saint Helens School Gym', 53, 54);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 24, 'Understudy', 'The Veil', 17, 'II', 'Mount Saint Helens School Gym', 54, 56);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 25, 'Growing Up Catholic', 'Growing Up Catholic', 18, 'II', 'Mount Saint Helens School Gym', 56, 57);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 26, 'The Summons', null, null, 'II', 'Mount Saint Helens School Gym', 57, 58);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 27, 'Clean Out the Freezer', 'Clean Out the Freezer', 19, 'II', 'Mount Saint Helens School Gym', 58, 59);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 28, 'The Nurse', null, null, 'II', 'Mount Saint Helens School Gym', 59, 60);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 29, 'Just A Coupl\'a Sisters', 'Just A Coupl\'a Sisters', 22, 'II', 'Mount Saint Helens School Gym', 60, 63);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 30, 'Soup\'s On', 'Soup\'s On', 23, 'II', 'Mount Saint Helens School Gym', 63, 66);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 31, 'Julia, Child of God', null, null, 'II', 'Mount Saint Helens School Gym', 66, 69);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 32, 'Second Fiddle Reprise', 'Second Fiddle Reprise', 24, 'II', 'Mount Saint Helens School Gym', 69, 70);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 33, 'I Just Want to Be A Star', 'I Just Want to Be A Star', 25, 'II', 'Mount Saint Helens School Gym', 70, 72);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 34, 'Star Playoff', 'Star Playoff(25A)', 25, 'II', 'Mount Saint Helens School Gym', 72, 73);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 35, 'The Drive-In', 'The Drive-In', 26, 'II', 'Mount Saint Helens School Gym', 73, 75);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 36, 'Nunsmoke', 'Nunsmoke', 27, 'II', 'Mount Saint Helens School Gym', 75, 75);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 37, 'I Could\'ve Gone to Nashville', 'I Could\'ve Gone to Nashville', 28, 'II', 'Mount Saint Helens School Gym', 75, 78);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 38, 'Who Are You?', 'Nashville Playoff(28A)', 28, 'II', 'Mount Saint Helens School Gym', 78, 78);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 39, 'Gloria In Excelsis Deo', 'Gloria In Excelsis Deo', 29, 'II', 'Mount Saint Helens School Gym', 78, 80);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 40, 'Holier Than Thou', 'Holier Than Thou', 30, 'II', 'Mount Saint Helens School Gym', 80, 84);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 41, 'Nunsense Reprise', 'Nunsense Reprise', 31, 'II', 'Mount Saint Helens School Gym', 84, 84);
INSERT INTO scene (musical_name, scene_number, scene_name, song_title, song_id, act, location, script_page_begin, script_page_end) VALUES ('Nunsense', 42, 'Bows and Exit Music', 'Bows and Exit Music', 32, 'II', 'Mount Saint Helens School Gym', 84, 84);

-- scene_part table rows
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (1, 1, 5, 'Wicked');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (2, 2, 3, 'Wicked');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (3, 3, 2, 'Wicked');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (4, 3, 3, 'Wicked');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (5, 3, 4, 'Wicked');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (6, 4, 2, 'Wicked');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (7, 4, 3, 'Wicked');

INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 100, 19, 'Nunsense');

INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 1, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 1, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 1, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 1, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 2, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 3, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 4, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 4, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 5, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 6, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 6, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 6, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 7, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 7, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 8, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 8, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 9, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 9, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 9, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 9, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 10, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 10, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 11, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 12, 4, 'Nunsense');

INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 13, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 13, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 13, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 13, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 13, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 13, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 14, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 15, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 16, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 17, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 17, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 17, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 18, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 19, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 20, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 21, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 22, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 23, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 24, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 25, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 26, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 27, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 28, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 28, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 28, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 28, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 28, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 28, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 29, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 29, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 30, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 31, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 32, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 33, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 34, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 34, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 34, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 34, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 35, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 35, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 35, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 35, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 35, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 36, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 36, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 36, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 36, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 36, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 37, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 38, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 39, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 40, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 41, 19, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 1, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 2, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 3, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 4, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 5, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 6, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 7, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 8, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 9, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 10, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 11, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 12, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 13, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 14, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 15, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 16, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 17, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 18, 'Nunsense');
INSERT INTO scene_part (scene_part_pk, scene_number, part_number, musical_name) VALUES (null, 42, 19, 'Nunsense');


-- conflict table not implemented as part of final project, but necessary for full functionality
INSERT INTO conflict (conflict_id, castmember_id, day_of_week, conflict_date, conflict_time, conflict_name, conflict_approved) VALUES (1, 4, 'Wednesday', null, null, 'dentist', 1);
INSERT INTO conflict (conflict_id, castmember_id, day_of_week, conflict_date, conflict_time, conflict_name, conflict_approved) VALUES (2, 2, null, '2023-01-03', null, 'did not feel like coming to rehearsal', 0);

-- rehearsal table not implemented as part of final project, but necessary for full functionality
INSERT INTO rehearsal (rehearsal_id, scene_number, day_of_week, rehearsal_date, rehearsal_start_time, rehearsal_end_time) VALUES (1, 3, 'Tuesday', '2023-01-03', '15:30:00', '17:30:00'); 
INSERT INTO rehearsal (rehearsal_id, scene_number, day_of_week, rehearsal_date, rehearsal_start_time, rehearsal_end_time) VALUES (2, 4, 'Wednesday', '2023-01-04', '18:00:00', '20:30:00');
